# Generated by Django 5.0.6 on 2024-07-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.CharField(blank=True, max_length=50, null=True)),
                ('aluno', models.CharField(blank=True, max_length=50, null=True)),
                ('instituto', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('disciplina', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
