# Dockerfile-frontend

# Use uma imagem base com Node.js 20
FROM node:20.13.1

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos do projeto para o diretório de trabalho
COPY package*.json ./
RUN npm install

COPY . .

# Compila o projeto React
RUN npm run build

# Exponha a porta na qual o aplicativo vai rodar
EXPOSE 3000

# Define o comando para iniciar o servidor
CMD ["npx", "serve", "-s", "build"]

