# Dockerfile-frontend

# Use a imagem base do Node
FROM node:20.13.1

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos de configuração do projeto
COPY package*.json ./

# Instala as dependências
RUN npm install 
# Copia o código fonte da aplicação
COPY . .

RUN apt-get install -y xsel
# Executa o build da aplicação
RUN npm run build

# Instala o serve para servir os arquivos estáticos
RUN npm install -g serve


# Exponha a porta 3000
EXPOSE 3000

# Define o comando para iniciar o servidor
CMD ["serve", "-s", "build", "-l", "3000"]
