version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:3000"
    command: serve -s dist
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis  # Adicionando redis como dependência
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - DATABASE_ENGINE=django.db.backends.postgresql
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_HOST=inaudibly-flashy-flatfish.data-1.use1.tembo.io
      - DATABASE_PASSWORD=fNjEk6AZW4pz4vJx
      - DATABASE_PORT=5432
    stdin_open: true
    tty: true
    command: daphne -b 0.0.0.0 -p 8000 core.asgi:application

  db:
    image: postgres:15.8
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fNjEk6AZW4pz4vJx
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
