# Dockerfile-backend

# Use uma imagem base com Python 3.12
FROM python:3.12.3

# Define o diretório de trabalho
WORKDIR /app

# Instala dependências do sistema (se necessário)
RUN apt-get update && apt-get install -y build-essential libpq-dev

# Copia os arquivos de dependências para o diretório de trabalho
COPY requirements.txt ./

# Instala as dependências Python 
RUN apt-get install -y pandoc
RUN pip install -r requirements.txt 

# Adiciona a instalação de Django Channels com suporte a Daphne
RUN python -m pip install -U channels["daphne"]  
# Copia todo o restante do código da aplicação para o diretório de trabalho
COPY . .

# Garante que o diretório de arquivos estáticos existe
RUN mkdir -p /app/staticfiles

# Coleta arquivos estáticos
RUN python manage.py collectstatic --noinput

# Aplica migrações do banco de dados
RUN python manage.py migrate

# Exponha a porta na qual o Django vai rodar
EXPOSE 8000

# Define o comando para iniciar o servidor Daphne
CMD ["daphne", "-p", "8000", "core.asgi:application"]
