# Generated by Django 5.0.6 on 2024-08-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='session_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='session_id',
            field=models.UUIDField(),
        ),
    ]
