# Generated by Django 5.0.6 on 2024-08-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.BooleanField(default=False),
        ),
    ]
