# Generated by Django 5.0.6 on 2024-08-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
