# Generated by Django 5.0.6 on 2024-07-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_thesis_cidade_thesis_disciplina_thesis_institute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
